version: '2'
services:
   db:
      image: mongo:latest
      volumes:
        - "./.data/db:/var/lib/mongodb"
      restart: always
      expose:
        - "1234"
      environment:
         MONGO_USER: mongodb
         MONGO_DATA_DIR: /var/lib/mongodb
         MONGO_LOG_DIR: /var/log/mongodb
   nodejs:
        depends_on:
          - db
        build: .
        links:
          - db
        expose:
          - "1234"
        ports:
          - "80:8080"
          - "443:8080"
